authentik:
  # Use external secret for the secret key
  secret_key:
    valueFrom:
      secretKeyRef:
        name: authentik-secret-key
        key: AUTHENTIK_SECRET_KEY

  # Disable built-in PostgreSQL and Redis
  postgresql:
    enabled: false

  redis:
    enabled: false

  # Environment variables
  envValueFrom:
    AUTHENTIK_POSTGRESQL__HOST:
      secretKeyRef:
        name: authentik-db-secret
        key: AUTHENTIK_POSTGRESQL__HOST
    AUTHENTIK_POSTGRESQL__NAME:
      secretKeyRef:
        name: authentik-db-secret
        key: AUTHENTIK_POSTGRESQL__NAME
    AUTHENTIK_POSTGRESQL__USER:
      secretKeyRef:
        name: authentik-db-secret
        key: AUTHENTIK_POSTGRESQL__USER
    AUTHENTIK_POSTGRESQL__PASSWORD:
      secretKeyRef:
        name: authentik-db-secret
        key: AUTHENTIK_POSTGRESQL__PASSWORD
    AUTHENTIK_REDIS__HOST:
      secretKeyRef:
        name: authentik-redis-secret
        key: AUTHENTIK_REDIS__HOST
  
  envFrom:
    AUTHENTIK_LISTEN__HTTP: "0.0.0.0:9000"
    AUTHENTIK_LISTEN__HTTPS: "0.0.0.0:9443"

server:
  replicas: 1

  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

worker:
  replicas: 1

resources:
  server:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  worker:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
