apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: 2024.8.3
    helm:
      values: |
        authentik:
          postgresql:
            enabled: false
          redis:
            enabled: false
        envFrom:
        - secretRef:
            name: authentik-secrets
        server:
          replicas: 1
          service:
            type: ClusterIP
        worker:
          replicas: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
