apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: 2024.8.3
    helm:
      values: |
        authentik:
          postgresql:
            enabled: false
          redis:
            enabled: false
        global:
          env:
          - name: AUTHENTIK_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: authentik-secrets
                key: AUTHENTIK_SECRET_KEY
          - name: AUTHENTIK_POSTGRESQL__HOST
            valueFrom:
              secretKeyRef:
                name: authentik-secrets
                key: AUTHENTIK_POSTGRESQL__HOST
          - name: AUTHENTIK_POSTGRESQL__NAME
            valueFrom:
              secretKeyRef:
                name: authentik-secrets
                key: AUTHENTIK_POSTGRESQL__NAME
          - name: AUTHENTIK_POSTGRESQL__USER
            valueFrom:
              secretKeyRef:
                name: authentik-secrets
                key: AUTHENTIK_POSTGRESQL__USER
          - name: AUTHENTIK_POSTGRESQL__PASSWORD
            valueFrom:
              secretKeyRef:
                name: authentik-secrets
                key: AUTHENTIK_POSTGRESQL__PASSWORD
          - name: AUTHENTIK_REDIS__HOST
            valueFrom:
              secretKeyRef:
                name: authentik-secrets
                key: AUTHENTIK_REDIS__HOST
        server:
          replicas: 1
          service:
            type: ClusterIP
        worker:
          replicas: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
